plugins {
    id 'com.android.application'
}

android {
    namespace 'com.galaxywatchface.simpleanalogevent'
    compileSdk 34

    defaultConfig {
        applicationId 'com.galaxywatchface.simpleanalogevent'
        minSdk 34
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.getByName('debug')
        }
    }
}
